---
- name: Remove old static files
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }}/static state=absent

- name: Remove old uuid file
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }}/rkt-uuid state=absent

- include: ../../openslides-add-instance/tasks/recreate_units.yml

- name: Restart openslides Instance
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_{{ openslides_instance_id }}.service'
    state: restarted

- wait_for: path={{ openslides_instance_path }}/rkt-uuid

- pause: seconds=15

- shell: cat {{ openslides_instance_path }}/rkt-uuid
  register: rkt_uuid

- set_fact:
    openslides_rkt_manage: /usr/bin/rkt enter {{ rkt_uuid.stdout }} /app/manage.py

- name: Collect static
  sudo: yes
  sudo_user: root
  command: '{{ openslides_rkt_manage }} collectstatic --noinput --clear'

- name: Change file permissions
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }} recurse=yes owner={{ username_on_the_host}}

- name: Migrate database
  sudo: yes
  sudo_user: root
  command: '{{ openslides_rkt_manage }} migrate --noinput'

