---
- set_fact:
    openslides_instance_webprocesses: "{{ openslides_instance_webprocesses | default([]) + [item] }}"
  with_sequence: start=1 end={{openslides_instance_num_webprocesses}}

- name: Start openslides service
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_{{ openslides_instance_id }}_{{ item }}.service'
    enabled: yes
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Deactivate openslides proxy service
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_proxy_{{ openslides_instance_id }}_{{ item }}.service'
    enabled: yes
    state: started
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Deactivate openslides proxy socket
  sudo: yes
  sudo_user: root
  service:
    name: 'openslides_instance_proxy_{{ openslides_instance_id }}_{{ item }}.socket'
    enabled: yes
    state: started
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Create 502.html
  template:
    dest: "{{ openslides_instance_path }}/502.html"
    src: 502.html.j2
