---
- set_fact:
    openslides_instance_webprocesses: "{{ openslides_instance_webprocesses | default([]) + [item] }}"
  with_sequence: start=1 end={{openslides_instance_num_webprocesses}}

- set_fact:
    openslides_instance_workers: "{{ openslides_instance_workers | default([]) + [item] }}"
  with_sequence: start=1 end={{openslides_instance_num_workers}}

- name: Remove instance directory
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }} state=absent

- name: Remove ansible log file
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instances_dir }}/ansible.{{ openslides_instance_id }}.log.json state=absent

- name: Remove instance file
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_file }} state=absent

- name: Remove database
  sudo_user: postgres
  postgresql_db: name=openslides_{{ openslides_instance_id }}
                 state=absent
                 login_host={{ postgres_host }}
                 login_user={{ postgres_user }}
                 login_password={{ postgres_password }}

- include: remove_units.yml


- name: Reload systemd units
  command: systemctl daemon-reload
  sudo: yes
  sudo_user: root

- name: Remove nginx location config
  when: "'{{ openslides_instance_mode }}' == 'path'"
  sudo: yes
  sudo_user: root
  file: path=/etc/nginx/openslides/openslides_{{ openslides_instance_id }}.locations state=absent

- name: Remove nginx vhost config
  when: "'{{ openslides_instance_mode }}' == 'subdomain'"
  sudo: yes
  sudo_user: root
  file: path=/etc/nginx/openslides/openslides_{{ openslides_instance_id }}.conf state=absent

