---
- name: Remove instance directory
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }} state=absent

- name: Remove ansible log file
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instances_dir }}/ansible.{{ openslides_instance_id }}.log.json state=absent

- name: Remove instance file
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_file }} state=absent

- name: Remove database
  sudo_user: postgres
  postgresql_db: name=openslides_{{ openslides_instance_id }}
                 state=absent
                 login_host={{ postgres_host }}
                 login_user={{ postgres_user }}
                 login_password={{ postgres_password }}

- include: remove_units.yml

- name: Reload systemd units
  command: systemctl daemon-reload
  sudo: yes
  sudo_user: root
