---

- name: Create systemd units for openslides redis
  sudo: yes
  sudo_user: root
  template:
    dest: '/etc/systemd/system/{{ openslides_instance_service_name }}_redis.service'
    src: "./openslides_instance_redis.service.j2"

- name: Create systemd units for openslides
  include: create_service_unit.yml
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Create systemd proxy units for openslides
  sudo: yes
  sudo_user: root
  register: createInstanceProxyService
  template:
    dest: '/etc/systemd/system/openslides_instance_proxy_{{ openslides_instance_id }}_{{ item }}.service'
    src: "./openslides_instance_proxy.service.j2"
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Create openslides proxy service unit for socket activation
  sudo: yes
  sudo_user: root
  register: createInstanceSocket
  template:
    dest: '/etc/systemd/system/openslides_instance_proxy_{{ openslides_instance_id }}_{{ item }}.socket'
    src: "./openslides_instance_proxy.socket.j2"
  with_items: "{{ openslides_instance_webprocesses }}"

- name: Reload systemd units
  sudo: yes
  sudo_user: root
  when: createInstanceService.changed or createInstanceSocket.changed or createInstanceProxyService.changed
  command: systemctl daemon-reload

#- name: Start and enalbe nginx via socket activation
#  sudo: yes
#  sudo_user: root
#  service:
#    name: 'openslides_instance_proxy_{{ openslides_instance_id }}_{{ item }}.socket'
#    enabled: yes
#    state: started
#  with_items: "{{ openslides_instance_webprocesses }}"

- name: Start redis
  sudo: yes
  sudo_user: root
  service:
    name: '{{ openslides_instance_service_name }}_redis.service'
    enabled: yes
    state: started
