- set_fact:
    openslides_rkt_daphne: /usr/bin/rkt run
      --port=8000-tcp:{{ openslides_instance_port_base + item|int }}
      --set-env=PYTHONPATH=/data:/app
      --volume volume-data,kind=host,source={{ openslides_instance_path }},readOnly=false
      --volume volume-plugins,kind=host,source={{ openslides_instance_path }}/plugins {{ openslides_instance_image }}
      --user={{ openslides_uid }}
      --group={{ openslides_gid }}
      --exec /usr/local/bin/daphne -- openslides.asgi:channel_layer -p 8000 -b 0.0.0.0

- set_fact:
    daphne_number: "{{ item }}"

- name: Create systemd units for openslides
  sudo: yes
  sudo_user: root
  register: createInstanceService
  template:
    dest: '/etc/systemd/system/{{ openslides_instance_service_name }}_{{ item }}.service'
    src: "./openslides_instance.service.j2"
