---

- name: Remove systemd units
  include: remove_units.yml

- name: Create instance directory
  file: path={{ openslides_instance_path }} state=directory

- set_fact:
    openslides_instance_webprocesses: "{{ openslides_instance_webprocesses | default([]) + [item] }}"
  with_sequence: start=1 end={{openslides_instance_num_webprocesses}}

- set_fact:
    openslides_instance_workers: "{{ openslides_instance_workers | default([]) + [item] }}"
  with_sequence: start=1 end={{openslides_instance_num_workers}}

- getent: database=passwd

- name: Check variable openslides_secure_key
  when: not openslides_secure_key
  fail:
    msg: The variable openslides_secure_key is not set.

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- set_fact:
    username_on_the_host: "{{username_on_the_host.stdout}}"

- set_fact:
    openslides_uid: "{{ getent_passwd[username_on_the_host][1] }}"
    openslides_gid: "{{ getent_passwd[username_on_the_host][2] }}"

- name: Create nginx configuration
  include: create_nginx_conf.yml

- name: Create instance container
  include: create_container.yml

- set_fact:
    openslides_rkt_manage: "{{ openslides_rkt_simple }} /app/manage.py --"

- name: Create and start systemd units
  include: create_units.yml

- name: Start redis because migrations fail otherwise
  sudo: yes
  sudo_user: root
  service:
    name: '{{ openslides_instance_service_name }}_redis.service'
    enabled: yes
    state: started

- name: Initialize database
  include: init_instance_database.yml

- name: Stop redis
  sudo: yes
  sudo_user: root
  service:
    name: '{{ openslides_instance_service_name }}_redis.service'
    state: stopped

- stat: path={{ openslides_instance_path }}/static
  register: static_path

- name: Collect static
  sudo: yes
  sudo_user: root
  when: static_path.stat.exists == False
  command: '{{ openslides_rkt_manage }} collectstatic --noinput'

- name: Change file permissions
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }} recurse=yes owner={{ username_on_the_host}}

- name: mark instance installed
  file: path={{ openslides_instance_path }}/installed state=touch

- name: cleanup rkt containers
  sudo: yes
  sudo_user: root
  shell: rkt gc --grace-period=0
