---
# save pod manifeste
#- name: Get POD manifest for starting later
#  sudo: yes
#  sudo_user: root
#  command: /usr/bin/rkt cat-manifest {{ rkt_uuid.stdout }}
#  register: rkt_manifest
#- copy:
#    content: "{{ rkt_manifest.stdout }}"
#    dest: '{{ openslides_instance_path }}/rkt-manifest'

- getent: database=passwd

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- set_fact:
    username_on_the_host: "{{username_on_the_host.stdout}}"

- set_fact:
    openslides_uid: "{{ getent_passwd[username_on_the_host][1] }}"
    openslides_gid: "{{ getent_passwd[username_on_the_host][2] }}"

- name: Set rkt fact
  include: set_openslides_rkt_base.yml

#- set_fact:
#    openslides_rkt_base: /usr/bin/rkt run --pod-manifest={{ openslides_instance_path }}/rkt-manifest

- name: Remove systemd units
  include: remove_units.yml

- name: Recreate systemd units
  include: create_units.yml

