---
# save pod manifeste
#- name: Get POD manifest for starting later
#  sudo: yes
#  sudo_user: root
#  command: /usr/bin/rkt cat-manifest {{ rkt_uuid.stdout }}
#  register: rkt_manifest
#- copy:
#    content: "{{ rkt_manifest.stdout }}"
#    dest: '{{ openslides_instance_path }}/rkt-manifest'

- getent: database=passwd

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- set_fact:
    username_on_the_host: "{{username_on_the_host.stdout}}"

- set_fact:
    openslides_uid: "{{ getent_passwd[username_on_the_host][1] }}"
    openslides_gid: "{{ getent_passwd[username_on_the_host][2] }}"

- set_fact:
    openslides_rkt_base: /usr/bin/rkt run
      --uuid-file-save={{ openslides_instance_path }}/rkt-uuid
      {% for i in  openslides_instance_webprocesses%}--port={{8000+i|int}}-tcp:{{ openslides_instance_port_base + i|int }} {%endfor%}
      --set-env=PYTHONPATH=/data:/app
      --volume volume-data,kind=host,source={{ openslides_instance_path }},readOnly=false
      --volume volume-plugins,kind=host,source={{ openslides_instance_path }}/plugins {{ openslides_instance_image }}
      --user={{ openslides_uid }}
      --group={{ openslides_gid }}
      --exec

#- set_fact:
#    openslides_rkt_base: /usr/bin/rkt run --pod-manifest={{ openslides_instance_path }}/rkt-manifest

- name: Remove systemd units
  include: remove_units.yml

- name: Recreate systemd units
  include: create_units.yml

